# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: 'Lemon')
Ingredient.create(name: 'Vodka')
Ingredient.create(name: 'Sugar')
Ingredient.create(name: 'Ice')
Ingredient.create(name: 'Mint leaves')
Ingredient.create(name: 'Aperol')
Ingredient.create(name: 'Prosecco')
Ingredient.create(name: 'Soda')
Ingredient.create(name: 'Gin')
Ingredient.create(name: 'Sweet vermouth')
Ingredient.create(name: 'Campari')
Ingredient.create(name: 'Orange')
Ingredient.create(name: 'Oranges')
Ingredient.create(name: 'Orange juice')
Ingredient.create(name: 'Pineapple juice')
Ingredient.create(name: 'White rum')
Ingredient.create(name: 'Coconut cream')
Ingredient.create(name: 'Pineapple')
Ingredient.create(name: 'Peach schnapps')
Ingredient.create(name: 'Cranberry juice')
Ingredient.create(name: 'Cherries')
Ingredient.create(name: 'Cherry')
Ingredient.create(name: 'Tomato juice')
Ingredient.create(name: 'Lemon juice')
Ingredient.create(name: 'Tabasco')
Ingredient.create(name: 'Celery salt')
Ingredient.create(name: 'Black pepper')
Ingredient.create(name: 'Celery sticks')
Ingredient.create(name: 'Limes')
Ingredient.create(name: 'Golden caster sugar')
Ingredient.create(name: 'Cachaça')
Ingredient.create(name: 'Tequila')
Ingredient.create(name: 'Lime juice')
Ingredient.create(name: 'Cream soda')
Ingredient.create(name: 'Orange liqueur')
Ingredient.create(name: 'Cotton candy')
Ingredient.create(name: 'Sugar syrup')
Ingredient.create(name: 'Espresso coffee')
Ingredient.create(name: 'Coffee liqueur')
Ingredient.create(name: 'Coffee beans')
Ingredient.create(name: 'Worcestershire sauce')
Ingredient.create(name: 'Triple sec')
Ingredient.create(name: 'Salt')
Ingredient.create(name: 'Granulated sugar')
Ingredient.create(name: 'Grenadine')